package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
	"time"
)

// ---------------------------------------------------------------------------
// The tailnet policy
//
// Same four grants as the sandbox page, same labels. The sandbox says "first
// matching grant wins"; a real policy is a union of accepts, so the two agree on
// every allow and deny and disagree only on which rule gets the credit. Worth
// knowing before you compare the two side by side.
// ---------------------------------------------------------------------------

type Grant struct {
	Key    string   `json:"key"`
	Src    string   `json:"src"`
	Dst    string   `json:"dst"`
	Ports  []string `json:"ports"`
	Label  string   `json:"label"`
	Sub    string   `json:"sub,omitempty"`
	Danger bool     `json:"danger,omitempty"`
}

var Grants = []Grant{
	{Key: "laptop", Src: "tag:laptop", Dst: "tag:server", Ports: []string{"22"},
		Label: "tag:laptop → tag:server : 22"},
	{Key: "roam", Src: "tag:roam", Dst: "tag:server", Ports: []string{"22"},
		Label: "tag:roam → tag:server : 22"},
	{Key: "untrusted", Src: "tag:untrusted", Dst: "*", Ports: []string{"*"},
		Label: "tag:untrusted → * : *", Danger: true,
		Sub: "one tag, given everything — the over-broad grant"},
	{Key: "any", Src: "*", Dst: "*", Ports: []string{"*"},
		Label: "* → * : *", Danger: true,
		Sub: "membership becomes total access — the default nobody meant to keep"},
}

func (c *Controller) policyHuJSON(acl ACLState) string {
	var rules []string
	add := func(src, dst string, ports []string) {
		var dsts []string
		for _, p := range ports {
			dsts = append(dsts, fmt.Sprintf("%q", dst+":"+p))
		}
		rules = append(rules, fmt.Sprintf(
			"    { \"action\": \"accept\", \"src\": [%q], \"dst\": [%s] }",
			src, strings.Join(dsts, ", ")))
	}
	for _, g := range Grants {
		if acl.Grants[g.Key] {
			add(g.Src, g.Dst, g.Ports)
		}
	}
	if acl.Def == "accept" {
		add("*", "*", []string{"*"})
	}

	ssh := ""
	if acl.SSH {
		ssh = `
  "ssh": [
    {
      "action": "accept",
      "src":    ["tag:laptop", "tag:roam"],
      "dst":    ["tag:server"],
      "users":  ["root", "autogroup:nonroot"],
    },
  ],`
	}

	return fmt.Sprintf(`// Generated by the lab control server. Every line here came from a switch
// you flipped; nothing is decorative.
//
// Default action: %s
{
  "tagOwners": {
    "tag:server":    ["lab@"],
    "tag:laptop":    ["lab@"],
    "tag:roam":      ["lab@"],
    "tag:untrusted": ["lab@"],
  },%s
  "acls": [
%s
  ],
}
`, acl.Def, ssh, strings.Join(rules, ",\n"))
}

// applyPolicy writes the policy and pushes it to the coordination server, which
// distributes it to every node in seconds without anything restarting.
func (c *Controller) applyPolicy(ctx context.Context) error {
	s := c.Snapshot()
	body := c.policyHuJSON(s.ACL)
	path := c.StateFile("policy.hujson")
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return err
	}
	r, err := c.lab.Exec(ctx, "headscale", "headscale", "policy", "set", "-f", "/lab/state/policy.hujson")
	if err != nil {
		return err
	}
	if r.Code != 0 {
		return fmt.Errorf("headscale policy set: %s", r.Out())
	}
	c.saveDesired()
	return nil
}

func (c *Controller) PolicyText() string {
	return c.policyHuJSON(c.Snapshot().ACL)
}

// ---------------------------------------------------------------------------
// Setting one switch
//
// The UI sends the same paths the sandbox uses for its own state, so a reader
// moving between the two is moving between identical vocabularies.
// ---------------------------------------------------------------------------

var errUnknownPath = fmt.Errorf("unknown switch")

func (c *Controller) Set(ctx context.Context, path string, value any) Result {
	// Start from the shared truth, not from whatever this process last thought.
	// `docker compose --profile weak up` is a different process; without this,
	// the first thing the long-running server does after it is to push its own
	// stale policy over the one that was just applied.
	c.loadDesired()
	res := Result{OK: true, Rung: 0, Rule: path}

	boolOf := func() bool {
		switch v := value.(type) {
		case bool:
			return v
		case string:
			return v == "true" || v == "on"
		case float64:
			return v != 0
		}
		return false
	}
	strOf := func() string {
		if s, ok := value.(string); ok {
			return s
		}
		return fmt.Sprint(value)
	}
	intOf := func() int {
		switch v := value.(type) {
		case float64:
			return int(v)
		case string:
			n, _ := strconv.Atoi(v)
			return n
		}
		return 0
	}

	switch {
	// ---- machines -------------------------------------------------------
	case strings.HasPrefix(path, "machines.") && strings.HasSuffix(path, ".online"):
		id := strings.TrimSuffix(strings.TrimPrefix(path, "machines."), ".online")
		return c.setOnline(ctx, id, boolOf())

	case path == "machines.evil-box.onTailnet":
		return c.evilJoin(ctx, boolOf())

	case path == "machines.evil-box.signed":
		// See lab/README.md: Headscale has no tailnet lock, so "signed" here
		// means the operator deliberately handed this machine a key.
		return c.evilJoin(ctx, boolOf())

	case path == "segmentShared":
		return c.setOnPath(ctx, boolOf())

	// ---- the network ----------------------------------------------------
	case strings.HasPrefix(path, "links.") && strings.HasSuffix(path, ".up"):
		id := strings.TrimSuffix(strings.TrimPrefix(path, "links."), ".up")
		return c.setLink(ctx, id, boolOf())

	case strings.HasPrefix(path, "links.") && strings.HasSuffix(path, ".loss"):
		id := strings.TrimSuffix(strings.TrimPrefix(path, "links."), ".loss")
		st := c.Snapshot()
		return c.shape(ctx, id, intOf(), st.Links[id].Delay)

	case strings.HasPrefix(path, "links.") && strings.HasSuffix(path, ".delay"):
		id := strings.TrimSuffix(strings.TrimPrefix(path, "links."), ".delay")
		st := c.Snapshot()
		return c.shape(ctx, id, st.Links[id].Loss, intOf())

	case strings.HasPrefix(path, "links.") && strings.HasSuffix(path, ".udpBlocked"):
		id := strings.TrimSuffix(strings.TrimPrefix(path, "links."), ".udpBlocked")
		return c.blockUDP(ctx, id, boolOf())

	// ---- tailnet policy -------------------------------------------------
	case path == "acl.def":
		c.with(func(s *State) { s.ACL.Def = strOf() })
		return c.pushPolicy(ctx, res, "policy default action -> "+strOf())

	case strings.HasPrefix(path, "acl.grants."):
		k := strings.TrimPrefix(path, "acl.grants.")
		v := boolOf()
		c.with(func(s *State) { s.ACL.Grants[k] = v })
		return c.pushPolicy(ctx, res, "grant "+k+" -> "+strconv.FormatBool(v))

	case path == "acl.ssh":
		v := boolOf()
		c.with(func(s *State) { s.ACL.SSH = v })
		out := c.pushPolicy(ctx, res, "tailscale ssh -> "+strconv.FormatBool(v))
		for _, id := range []string{"lab-vps", "lab-ubuntu", "lab-roam"} {
			arg := "--ssh=false"
			if v {
				arg = "--ssh"
			}
			_, _ = c.lab.Exec(ctx, id, "tailscale", "set", arg)
		}
		out.Cmds = append(out.Cmds, "tailscale set --ssh"+map[bool]string{true: "", false: "=false"}[v])
		return out

	case path == "acl.lock":
		return c.setLock(ctx, boolOf())

	case path == "acl.expiry":
		return c.setExpiry(ctx, boolOf())

	// ---- the host -------------------------------------------------------
	case path == "vps.ufwDefaultDeny":
		return c.ufw(ctx, boolOf(),
			[]string{"ufw", "default", "deny", "incoming"},
			[]string{"ufw", "default", "allow", "incoming"})

	case path == "vps.allowTailscale0":
		return c.ufw(ctx, boolOf(),
			[]string{"ufw", "allow", "in", "on", "tailscale0"},
			[]string{"ufw", "--force", "delete", "allow", "in", "on", "tailscale0"})

	case path == "vps.allowPublic22":
		return c.ufw(ctx, boolOf(),
			[]string{"ufw", "allow", "22/tcp"},
			[]string{"ufw", "--force", "delete", "allow", "22/tcp"})

	case path == "vps.dockerPublish":
		return c.dockerTrap(ctx, boolOf())

	case path == "vps.sshdListen":
		return c.sshdListen(ctx, strOf())

	case path == "vps.passwordAuth":
		return c.sshdOption(ctx, "PasswordAuthentication", map[bool]string{true: "yes", false: "no"}[boolOf()])

	case path == "vps.permitRoot":
		return c.sshdOption(ctx, "PermitRootLogin", map[bool]string{true: "yes", false: "prohibit-password"}[boolOf()])
	}

	res.OK = false
	res.Why = errUnknownPath.Error() + ": " + path
	return res
}

func (c *Controller) pushPolicy(ctx context.Context, res Result, what string) Result {
	res.Cmds = append(res.Cmds, "headscale policy set -f policy.hujson   # "+what)
	if err := c.applyPolicy(ctx); err != nil {
		res.OK = false
		res.Why = err.Error()
		return res
	}
	res.Why = "policy updated and pushed to every node"
	return res
}

// ---------------------------------------------------------------------------
// Machines
// ---------------------------------------------------------------------------

func (c *Controller) setOnline(ctx context.Context, id string, up bool) Result {
	res := Result{Rung: 1, Rule: id}
	var err error
	if up {
		res.Cmds = []string{"docker compose start " + id}
		err = c.lab.Start(ctx, id)
		res.Why = id + " is running"
	} else {
		res.Cmds = []string{"docker compose stop " + id}
		err = c.lab.Stop(ctx, id)
		res.Why = id + " is stopped — nothing it was doing survives"
	}
	if err != nil {
		res.Why = err.Error()
		return res
	}
	res.OK = true
	c.Observe(ctx)
	return res
}

// evilJoin hands the attacker a working key, or takes it away. This is the
// closest a Headscale lab gets to "somebody leaked a node key".
func (c *Controller) evilJoin(ctx context.Context, join bool) Result {
	res := Result{Rung: 1, Rule: "evil-box"}
	if !c.lab.Running(ctx, "evil-box") {
		res.Why = "evil-box is not running. Start it first — it never starts on its own."
		return res
	}
	if !join {
		res.Cmds = []string{"tailscale logout   # on evil-box"}
		r, _ := c.lab.Exec(ctx, "evil-box", "tailscale", "logout")
		res.OK = true
		res.Raw = r.Out()
		res.Why = "evil-box has no tailnet session any more"
		c.Observe(ctx)
		return res
	}

	s := c.Snapshot()
	if s.ACL.Lock {
		res.OK = false
		res.Rung = 1
		res.Rule = "no key exists for a machine nobody authorised"
		res.Why = "Refused before any policy was consulted. With 'tailnet lock' on, the " +
			"lab never issues a key this machine could present, so no peer will complete " +
			"a handshake with it. Turn lock off and try the same thing again."
		return res
	}
	if c.untrustedKey == "" {
		res.Why = "no spare key was created at boot — try `make reset`"
		return res
	}
	res.Cmds = []string{"tailscale up --login-server=https://headscale:8443 --authkey=tskey-LEAKED   # on evil-box"}
	r, err := c.lab.Exec(ctx, "evil-box", "tailscale", "up",
		"--login-server=https://headscale:8443",
		"--authkey="+c.untrustedKey,
		"--hostname=evil-box", "--accept-routes=false", "--accept-dns=false", "--timeout=30s")
	res.Raw = r.Out()
	if err != nil || r.Code != 0 {
		res.Why = "the join failed: " + r.Out()
		return res
	}
	c.EnsureTags(ctx)
	_ = c.applyPolicy(ctx)
	res.OK = true
	res.Danger = true
	res.Why = "evil-box is on the tailnet. From here the only thing between it and your " +
		"machines is the policy."
	c.Observe(ctx)
	return res
}

// setOnPath puts evil-box in the position a café network puts it in: the router
// lab-ubuntu's traffic leaves through.
func (c *Controller) setOnPath(ctx context.Context, on bool) Result {
	res := Result{Rung: 2, Rule: "lab-ubuntu's default route"}
	if !c.lab.Running(ctx, "evil-box") {
		res.Why = "evil-box is not running."
		return res
	}
	evilLAN := c.lab.IPOn(ctx, "evil-box", "lan-ubuntu")
	if on && evilLAN == "" {
		res.Why = "evil-box is not attached to lab-ubuntu's segment. Start the lab with " +
			"`docker compose --profile attack up -d` so it gets that interface."
		return res
	}

	if on {
		r1, _ := c.lab.Exec(ctx, "evil-box", "lab-onpath", "on")
		r2, err := c.lab.Exec(ctx, "lab-ubuntu", "ip", "route", "replace", "default", "via", evilLAN)
		res.Cmds = []string{
			"lab-onpath on   # on evil-box: ip_forward + masquerade",
			"ip route replace default via " + evilLAN + "   # on lab-ubuntu",
		}
		res.Raw = r1.Out() + "\n" + r2.Out()
		if err != nil {
			res.Why = err.Error()
			return res
		}
		res.OK, res.Danger = true, true
		res.Why = "every packet lab-ubuntu sends now passes through evil-box's kernel. " +
			"It can see all of it."
	} else {
		gw := c.gatewayFor("lab-ubuntu")
		r1, _ := c.lab.Exec(ctx, "lab-ubuntu", "ip", "route", "replace", "default", "via", gw)
		r2, _ := c.lab.Exec(ctx, "evil-box", "lab-onpath", "off")
		res.Cmds = []string{
			"ip route replace default via " + gw + "   # on lab-ubuntu",
			"lab-onpath off   # on evil-box",
		}
		res.Raw = r1.Out() + "\n" + r2.Out()
		res.OK = true
		res.Why = "lab-ubuntu routes through its own NAT again"
	}
	c.with(func(s *State) { s.SegmentShared = on })
	c.saveDesired()
	return res
}

func (c *Controller) gatewayFor(id string) string {
	switch id {
	case "lab-ubuntu":
		return "10.0.13.254"
	case "lab-roam":
		return "10.0.27.254"
	case "evil-box":
		return "10.0.66.254"
	}
	return ""
}

// ---------------------------------------------------------------------------
// The network — the three levers chapter 13 shapes by hand
// ---------------------------------------------------------------------------

func (c *Controller) setLink(ctx context.Context, id string, up bool) Result {
	res := Result{Rung: 1, Rule: id + " eth0"}
	state := "down"
	if up {
		state = "up"
	}
	res.Cmds = []string{"ip link set eth0 " + state + "   # on " + id}
	r, err := c.lab.Exec(ctx, id, "ip", "link", "set", "eth0", state)
	res.Raw = r.Out()
	if err != nil {
		res.Why = err.Error()
		return res
	}
	res.OK = true
	if up {
		// Taking an interface down drops every route through it, including the
		// one pointing at this machine's NAT router. The kernel puts back the
		// on-link route and nothing else, so without this the machine comes
		// back with a working cable and nowhere to send anything.
		if gw := c.gatewayFor(id); gw != "" {
			rr, _ := c.lab.Exec(ctx, id, "ip", "route", "replace", "default", "via", gw)
			res.Raw += "\n" + rr.Out()
			res.Cmds = append(res.Cmds, "ip route replace default via "+gw+"   # on "+id)
		}
		res.Why = "eth0 is back. Watch what reconnects on its own and what does not."
	} else {
		res.Why = "eth0 is down on " + id + " — nothing leaves the machine. " +
			"This is the tunnel, and it is the whole reason chapter 03 exists."
	}
	c.observeLinks(ctx)
	return res
}

func (c *Controller) shape(ctx context.Context, id string, loss, delay int) Result {
	res := Result{Rung: 2, Rule: "tc netem on " + id}
	_, _ = c.lab.Sh(ctx, id, "tc qdisc del dev eth0 root 2>/dev/null || true")
	if loss == 0 && delay == 0 {
		res.OK = true
		res.Cmds = []string{"tc qdisc del dev eth0 root   # on " + id}
		res.Why = "the link is clean again"
		c.observeLinks(ctx)
		return res
	}
	cmd := "tc qdisc add dev eth0 root netem"
	if loss > 0 {
		cmd += fmt.Sprintf(" loss %d%%", loss)
	}
	if delay > 0 {
		cmd += fmt.Sprintf(" delay %dms %dms", delay, delay/4)
	}
	res.Cmds = []string{cmd + "   # on " + id}
	r, err := c.lab.Sh(ctx, id, cmd)
	res.Raw = r.Out()
	if err != nil || r.Code != 0 {
		res.Why = "tc refused: " + r.Out()
		return res
	}
	res.OK = true
	res.LossPct = float64(loss)
	res.Why = fmt.Sprintf("%s now loses %d%% of packets and adds %dms — a bad café, on purpose", id, loss, delay)
	c.observeLinks(ctx)
	return res
}

func (c *Controller) blockUDP(ctx context.Context, id string, block bool) Result {
	res := Result{Rung: 2, Rule: "udp/41641 on " + id}
	if block {
		script := strings.Join([]string{
			"nft add table inet lab",
			"nft 'add chain inet lab out { type filter hook output priority 0 ; }'",
			"nft add rule inet lab out udp dport 41641 drop",
			"nft add rule inet lab out udp sport 41641 drop",
		}, " && ")
		res.Cmds = []string{
			"nft add table inet lab",
			"nft add chain inet lab out { type filter hook output priority 0 \\; }",
			"nft add rule inet lab out udp dport 41641 drop",
			"nft add rule inet lab out udp sport 41641 drop",
		}
		r, err := c.lab.Sh(ctx, id, script)
		res.Raw = r.Out()
		if err != nil || r.Code != 0 {
			res.Why = "nft refused: " + r.Out()
			return res
		}
		res.OK = true
		res.Why = "WireGuard's UDP port is dropped on " + id + ". Give it a few seconds and " +
			"the session should reappear over DERP, on TCP 443 — watch the path chip change."
	} else {
		res.Cmds = []string{"nft delete table inet lab"}
		r, _ := c.lab.Sh(ctx, id, "nft delete table inet lab 2>/dev/null || true")
		res.Raw = r.Out()
		res.OK = true
		res.Why = "UDP is allowed again; the direct path should come back on its own"
	}
	c.observeLinks(ctx)
	return res
}

// ---------------------------------------------------------------------------
// Tailnet lock and key expiry — the two places Headscale is not Tailscale
// ---------------------------------------------------------------------------

func (c *Controller) setLock(ctx context.Context, on bool) Result {
	res := Result{OK: true, Rung: 1, Rule: "tailnet lock (lab equivalent)"}
	c.with(func(s *State) { s.ACL.Lock = on })
	if on {
		res.Why = "No key exists for a machine you did not authorise. A node key on its own " +
			"buys nothing — which is the property tailnet lock gives you on real Tailscale. " +
			"Headscale has no tailnet lock; lab/README.md says what this stands in for."
		if c.lab.Running(ctx, "evil-box") {
			_, _ = c.lab.Exec(ctx, "evil-box", "tailscale", "logout")
			res.Cmds = []string{"tailscale logout   # on evil-box, its key no longer works"}
		}
	} else {
		res.Danger = true
		res.Why = "A reusable key now exists that anybody holding it can join with. That is " +
			"what a leaked key is worth when nothing has to vouch for it."
	}
	c.saveDesired()
	c.Observe(ctx)
	return res
}

func (c *Controller) setExpiry(ctx context.Context, on bool) Result {
	res := Result{Rung: 1, Rule: "key expiry"}
	if on {
		c.with(func(s *State) { s.ACL.Expiry = on })
		c.saveDesired()
		res.OK = true
		res.Why = "Every node in this lab already carries a real expiry — you can read it in " +
			"`headscale nodes list`. Nothing to do."
		res.Cmds = []string{"headscale nodes list -o json | jq '.[].expiry'"}
		return res
	}
	// The honest answer, which is more useful than a switch that lies.
	res.OK = false
	res.Rung = 0
	res.Rule = "Headscale has no per-node 'disable key expiry'"
	res.Why = "The sandbox can switch this off because it is a model. This lab cannot, " +
		"because Headscale does not expose it — and a real stack refusing to be made " +
		"unsafe the way the model says is exactly the kind of gap this pair exists to " +
		"find. The audit reads the real expiry either way, so the score stays honest."
	return res
}

// ---------------------------------------------------------------------------
// The host
// ---------------------------------------------------------------------------

func (c *Controller) ufw(ctx context.Context, on bool, add, del []string) Result {
	argv := add
	if !on {
		argv = del
	}
	res := Result{Rung: 4, Rule: strings.Join(argv, " "), Cmds: []string{"sudo " + strings.Join(argv, " ") + "   # on lab-vps"}}
	r, err := c.lab.Exec(ctx, "lab-vps", argv...)
	res.Raw = r.Out()
	if err != nil {
		res.Why = err.Error()
		return res
	}
	res.OK = r.Code == 0
	if !res.OK {
		res.Why = "ufw refused: " + r.Out()
	} else {
		res.Why = "ufw updated. Read the rules tab, then probe — the two do not always agree, " +
			"and the times they do not are the interesting ones."
	}
	c.observeVPS(ctx)
	return res
}

func (c *Controller) dockerTrap(ctx context.Context, on bool) Result {
	arg := "off"
	if on {
		arg = "on"
	}
	res := Result{Rung: 4, Rule: "DOCKER-USER / DOCKER chains on lab-vps"}
	res.Cmds = []string{"lab-docker-trap " + arg + "   # on lab-vps: the rules dockerd writes"}
	r, err := c.lab.Exec(ctx, "lab-vps", "lab-docker-trap", arg)
	res.Raw = r.Out()
	if err != nil || r.Code != 0 {
		res.Why = "the trap could not be set: " + r.Out()
		return res
	}
	res.OK = true
	res.Danger = on
	if on {
		res.Why = "Port 8080 now forwards to a container, through chains that sit ahead of " +
			"ufw's. ufw will still tell you the default policy is deny."
	} else {
		res.Why = "the published port is gone"
	}
	c.observeVPS(ctx)
	return res
}

// sshdConf is the one file the lab rewrites. It has to be one file, and every
// setting has to live in it, because sshd takes the FIRST value it finds for a
// keyword across the whole of sshd_config.d — so dropping a second file later in
// the sort order changes nothing at all, silently, and the switch looks broken.
const sshdConf = "/etc/ssh/sshd_config.d/10-lab-runtime.conf"

func sshdRewrite(key, value string) string {
	return fmt.Sprintf(
		`touch %[1]s; sed -i '/^%[2]s /d' %[1]s; printf '%%s %%s\n' '%[2]s' '%[3]s' >> %[1]s; `+
			`pkill sshd; sleep 1; /usr/sbin/sshd`, sshdConf, key, value)
}

func (c *Controller) sshdListen(ctx context.Context, mode string) Result {
	res := Result{Rung: 5, Rule: "sshd ListenAddress"}
	addr := "0.0.0.0"
	if mode == "tailnet" {
		addr = c.tsAddr(ctx, "lab-vps")
		if addr == "" {
			res.Why = "lab-vps has no tailnet address yet, so there is nothing to bind to"
			return res
		}
	}
	res.Cmds = []string{
		"sed -i 's/^ListenAddress.*/ListenAddress " + addr + "/' /etc/ssh/sshd_config",
		"systemctl restart ssh",
	}
	r, err := c.lab.Sh(ctx, "lab-vps", sshdRewrite("ListenAddress", addr)+
		"; ss -tlnp 2>/dev/null | head -4")
	res.Raw = r.Out()
	if err != nil {
		res.Why = err.Error()
		return res
	}
	res.OK = true
	if mode == "tailnet" {
		res.Why = "sshd is bound to " + addr + " only. A packet arriving on eth0 will now be " +
			"permitted by every firewall and answered by nothing — that is a rung-5 failure, " +
			"and no rule you can read explains it."
	} else {
		res.Why = "sshd is back on 0.0.0.0 and answers on every interface"
	}
	c.observeVPS(ctx)
	return res
}

func (c *Controller) sshdOption(ctx context.Context, key, value string) Result {
	res := Result{Rung: 5, Rule: key + " " + value}
	res.Cmds = []string{
		fmt.Sprintf("sed -i 's/^#\\?%s.*/%s %s/' /etc/ssh/sshd_config", key, key, value),
		"systemctl reload ssh",
	}
	r, err := c.lab.Sh(ctx, "lab-vps", sshdRewrite(key, value)+
		fmt.Sprintf("; sshd -T 2>/dev/null | grep -i '^%s'", strings.ToLower(key)))
	res.Raw = r.Out()
	if err != nil {
		res.Why = err.Error()
		return res
	}
	res.OK = true
	res.Danger = value == "yes"
	res.Why = "sshd now reports: " + strings.TrimSpace(r.Stdout)
	c.observeVPS(ctx)
	return res
}

// ---------------------------------------------------------------------------
// The probe — the five-rung ladder, walked against real kernels
//
// The sandbox works the rung out from its model. This works it out from
// evidence: it watches the destination while the source connects. If nothing
// arrives, the tailnet refused it and the far machine never heard about it
// (rung 3). If something arrives and dies, the host firewall dropped it
// (rung 4). If something arrives and is refused, nothing was listening
// (rung 5). That asymmetry is chapter 14's callout, and here it is measured
// rather than asserted.
// ---------------------------------------------------------------------------

// noPeerInNetmap is what the ladder says when both ends hold a tailnet session
// and the far machine is not in the near one's netmap at all. It is a rung-3
// denial with a distinguishing feature: the policy removed the peer rather than
// dropping its packets, so there is nothing to capture on the far machine and
// no log line to go looking for. Saying that out loud is the whole point —
// "nothing arrived and nothing was logged" is the denial people misread as a
// broken network.
func noPeerInNetmap(from, to string) Result {
	return Result{
		From: from, To: to, Rung: 3, Path: "direct",
		Rule: "the tailnet policy refused it — " + to + " is not even in " + from + "'s netmap",
		Why: "Nothing reached " + to + ", and " + from + " cannot see that it exists. " +
			"The policy removed the peer rather than dropping its packets, so there is " +
			"no log line on " + to + " to find.",
		Cmds: []string{"tailscale status   # on " + from + ": " + to + " is absent"},
	}
}

// tailnetPath reads `tailscale ping`'s output and says which way this pair
// settled on. The answer is the last line that reported a pong, not the last
// line: ping prints a summary underneath ("direct connection not established")
// and reading that as the verdict turns every relayed session into no session
// at all. ok is false when nothing ponged, which is a pair with two sessions
// and no path between them — rung 2, and a different finding from a policy
// denial.
func tailnetPath(pingOut string) (path, rule, why string, ok bool) {
	pong := lastLineContaining(pingOut, "pong from")
	switch {
	case strings.Contains(pong, "via DERP"):
		return "relay", "relayed through DERP — no direct path was available: " + pong, "", true
	case pong != "":
		return "direct", "direct — both NATs held a mapping open and the punch completed: " + pong, "", true
	default:
		r := lastLine(pingOut)
		return "", r, "Both ends have a tailnet session and no path between them: " + r, false
	}
}

// knock is the evidence one connection attempt produced, at both of its ends:
// what `nc -vz` said where it started, and what `tcpdump` caught where it was
// aimed. Rungs 3, 4 and 5 are a pure function of those two strings plus the
// interface the capture was watching, and keeping it a pure function is the
// only reason the ladder can be tested without a tailnet, a kernel or a
// container.
//
// The asymmetry it encodes is chapter 14's callout and the reason the lab
// exists. Nothing arrived → the tailnet refused it and the far machine was
// never involved. It arrived and died quietly → the host firewall dropped it,
// and that one is visible on the machine. It arrived and was refused → every
// rule permitted it and nothing was listening, which is usually a bind address
// rather than a rule.
type knock struct {
	from, to   string
	iface      string // the interface tcpdump was watching on `to`
	addr, port string
	out        string // `nc -vz -w 4 <addr> <port> 2>&1; echo "rc=$?"`
	capture    string // tcpdump's line, or empty if nothing arrived
}

// reached is nc's own exit status, which is the only thing that settles whether
// the connection completed. The banner it prints on success is not always the
// same sentence across nc implementations; the return code is.
func (k knock) reached() bool { return strings.Contains(k.out, "rc=0") }

func (k knock) refused() bool { return strings.Contains(strings.ToLower(k.out), "refused") }

// arrived asks the far machine, not the near one. This is the measurement that
// separates a rung-3 denial from a rung-4 one, and there is no way to make it
// from the sending side.
func (k knock) arrived() bool { return strings.TrimSpace(k.capture) != "" }

func (k knock) classify() (rung int, ok bool, rule, why string) {
	if k.reached() {
		return 5, true, "", "reached " + k.addr + ":" + k.port
	}
	if !k.arrived() {
		// Nothing turned up at the far end. Over the tailnet that is the
		// policy; over the ordinary network it means there is no path at all,
		// which is a claim about routing rather than about rules.
		if k.iface == "tailscale0" {
			return 3, false, "the tailnet policy refused it",
				"Nothing reached " + k.to + ". The tailnet dropped it before the far " +
					"machine was involved, so there is no log line on " + k.to + " to find — " +
					"which is exactly how a rung-3 denial feels when you are debugging one."
		}
		return 2, false, "",
			"Nothing arrived at " + k.to + " at all. There is no path between " +
				"these two right now."
	}
	if k.refused() {
		return 5, false, "the firewall permitted it — that is not the same as an answer",
			"The packet arrived and was refused. Every rule allowed it and nothing " +
				"was listening on an address this path reaches. Usually a bind address, " +
				"not a rule."
	}
	return 4, false, "the host firewall dropped it",
		"The packet reached " + k.to + " — you can see it in the capture — and the " +
			"box dropped it. Unlike a rung-3 denial, this one is visible on the machine."
}

var rttRe = regexp.MustCompile(`= [\d.]+/([\d.]+)/`)
var lossRe = regexp.MustCompile(`([\d.]+)% packet loss`)

func (c *Controller) Probe(ctx context.Context, from, to, port string) Result {
	c.loadDesired()
	res := Result{From: from, To: to, Port: port, Rung: 1}

	fm, ok1 := machineByID(from)
	tm, ok2 := machineByID(to)
	if !ok1 || !ok2 {
		res.Why = "no such machine"
		return res
	}
	_ = fm

	// ---- rung 1 · is anything alive? -----------------------------------
	if !c.lab.Running(ctx, from) {
		res.Why = from + " is not running"
		return res
	}
	if !c.lab.Running(ctx, to) {
		res.Why = to + " is not running"
		return res
	}
	fromST, _ := c.tailscaleStatus(ctx, from)
	toST, _ := c.tailscaleStatus(ctx, to)
	fromOn := fromST.BackendState == "Running"
	toOn := toST.BackendState == "Running"

	// ---- rung 2 · which way, if any? ------------------------------------
	res.Rung = 2
	var addr, iface string
	if fromOn && toOn {
		for _, p := range fromST.Peer {
			if p.HostName == to && len(p.TailAddr) > 0 {
				addr = p.TailAddr[0]
			}
		}
		iface = "tailscale0"
		if addr == "" {
			// Both ends have a session and the far machine is not in this
			// one's netmap at all. That is the policy at its most complete: a
			// peer you may not talk to is not merely blocked, it is not sent to
			// you. Rung 3, and there is nothing on the far machine to look at.
			r := noPeerInNetmap(from, to)
			r.Port = port
			return r
		}
	}
	if addr != "" {
		// `tailscale status` reports the path a session is *currently* using,
		// and a pair that has not spoken yet has no session at all — which
		// reads as "relay" when the truth is "nothing has tried". Ask the thing
		// whose whole job is to answer this instead. It keeps trying until it
		// gets a direct path or runs out of attempts, so what comes back is the
		// path this pair settles on rather than the first packet's fate.
		pr, _ := c.lab.Exec(ctx, from, "tailscale", "ping", "--c", "5", "--timeout", "8s", addr)
		// The last line is a summary ("direct connection not established"), so
		// the answer is the last line that actually reported a pong.
		path, rule, why, settled := tailnetPath(pr.Out())
		res.Path, res.Rule = path, rule
		if !settled {
			res.Why = why
			return res
		}
	}
	if addr == "" {
		// Not both on the tailnet: what is left is the ordinary network, and on
		// the ordinary network only lab-vps has an address anyone can reach.
		if to != "lab-vps" {
			res.Why = to + " is behind its own NAT and has no address the ordinary network " +
				"can reach. Without a tailnet there is no path at all — which is the thing " +
				"the tailnet is for."
			return res
		}
		addr = c.lab.IPOn(ctx, "lab-vps", "wan")
		res.Path = "public"
		res.Rule = "over the segment standing in for the public internet, to whatever answers"
		iface = c.ifaceOn(ctx, "lab-vps", addr)
	}
	if addr == "" {
		res.Why = "no address to aim at"
		return res
	}
	if res.Path == "" {
		res.Path = "relay"
		res.Rule = "a tailnet session exists but no path has settled yet"
	}

	// ---- rungs 3, 4 and 5 · watch the far end while we knock ------------
	capFile := "/tmp/probe-" + port + ".txt"
	_, _ = c.lab.Sh(ctx, to, fmt.Sprintf(
		`rm -f %s; (timeout 8 tcpdump -l -n -i %s -c 1 'tcp dst port %s' > %s 2>/dev/null &) ; sleep 1`,
		capFile, iface, port, capFile))

	ncr, _ := c.lab.Sh(ctx, from, fmt.Sprintf(
		`nc -vz -w 4 %s %s 2>&1; echo "rc=$?"`, addr, port))

	time.Sleep(700 * time.Millisecond)
	capr, _ := c.lab.Sh(ctx, to, "cat "+capFile+" 2>/dev/null; rm -f "+capFile)

	k := knock{from: from, to: to, iface: iface, addr: addr, port: port,
		out: ncr.Out(), capture: capr.Stdout}

	res.Cmds = []string{
		fmt.Sprintf("tcpdump -n -i %s -c 1 'tcp dst port %s'   # on %s", iface, port, to),
		fmt.Sprintf("nc -vz -w 4 %s %s   # on %s", addr, port, from),
	}
	res.Raw = strings.TrimSpace(k.out)
	if k.arrived() {
		res.Raw += "\n\n" + to + " saw it arrive:\n" + strings.TrimSpace(k.capture)
	} else {
		res.Raw += "\n\n" + to + " saw nothing arrive on " + iface + "."
	}

	rung, ok, rule, why := k.classify()
	res.Rung, res.OK, res.Why = rung, ok, why
	if rule != "" {
		res.Rule = rule
	}
	if !ok {
		return res
	}

	// ---- it worked. Now the numbers, measured rather than modelled. -----
	if tm.ID == "lab-vps" && port == "8080" {
		s := c.Snapshot()
		if s.VPS.UFWDefaultDeny && res.Path == "public" {
			res.Danger = true
			res.Rule = "DOCKER-USER accepted it before ufw's chain ever ran"
		}
	}

	if p, err := c.lab.Sh(ctx, from, fmt.Sprintf("ping -c 5 -W 2 -q %s 2>&1", addr)); err == nil {
		if m := rttRe.FindStringSubmatch(p.Stdout); len(m) == 2 {
			res.RTTMs, _ = strconv.ParseFloat(m[1], 64)
		}
		if m := lossRe.FindStringSubmatch(p.Stdout); len(m) == 2 {
			res.LossPct, _ = strconv.ParseFloat(m[1], 64)
		}
		res.Raw += "\n\n" + strings.TrimSpace(p.Stdout)
	}

	// 2 KiB through the path, and the kernel's own count of what that took.
	stat, _ := c.lab.Sh(ctx, from, fmt.Sprintf(
		`nstat -n >/dev/null 2>&1; dd if=/dev/zero bs=1024 count=2 2>/dev/null | timeout 4 nc -w 2 %s %s >/dev/null 2>&1; nstat 2>/dev/null | awk '/TcpOutSegs|TcpRetransSegs/ {print $1"="$2}'`,
		addr, port))
	res.Bytes = 2048
	for _, kv := range strings.Fields(stat.Stdout) {
		k, v, _ := strings.Cut(kv, "=")
		n, _ := strconv.Atoi(v)
		switch k {
		case "TcpOutSegs":
			res.Packets = n
		case "TcpRetransSegs":
			res.Retransmits = n
		}
	}
	return res
}

func lastLine(s string) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	return strings.TrimSpace(lines[len(lines)-1])
}

func lastLineContaining(s, want string) string {
	out := ""
	for _, l := range strings.Split(s, "\n") {
		if strings.Contains(l, want) {
			out = strings.TrimSpace(l)
		}
	}
	return out
}

func (c *Controller) ifaceOn(ctx context.Context, id, addr string) string {
	r, err := c.lab.Sh(ctx, id, fmt.Sprintf(`ip -o -4 addr show | awk '$4 ~ /^%s\// {print $2; exit}'`, addr))
	if err != nil {
		return "eth0"
	}
	if s := strings.TrimSpace(r.Stdout); s != "" {
		return s
	}
	return "eth0"
}

// ---------------------------------------------------------------------------
// Configurations
// ---------------------------------------------------------------------------

// ApplyPreset drives the whole stack into one of the four named states. The ids
// are the sandbox's ids, and `docker compose --profile weak up` runs exactly
// this.
func (c *Controller) ApplyPreset(ctx context.Context, id string) Result {
	c.loadDesired()
	p, ok := presetByID(id)
	if !ok {
		return Result{Why: "no configuration called " + id}
	}
	res := Result{OK: true, Rung: 0, Rule: p.Label, Why: p.Note}

	c.with(func(s *State) {
		s.ACL = p.ACL
		s.ACL.Grants = map[string]bool{}
		for k, v := range p.ACL.Grants {
			s.ACL.Grants[k] = v
		}
	})
	if err := c.applyPolicy(ctx); err != nil {
		res.Raw += "policy: " + err.Error() + "\n"
	}
	res.Cmds = append(res.Cmds, "headscale policy set -f policy.hujson")

	for _, m := range []string{"lab-vps", "lab-ubuntu", "lab-roam"} {
		if !c.lab.Running(ctx, m) {
			continue
		}
		if p.Tailnet {
			_, _ = c.lab.Sh(ctx, m, `tailscale status --json | grep -q '"BackendState": *"Running"' || tailscale up --login-server=https://headscale:8443 --authkey="$(cat /lab/state/authkey)" --hostname=`+m+` --accept-routes=false --accept-dns=false --timeout=30s`)
		} else {
			_, _ = c.lab.Exec(ctx, m, "tailscale", "down")
		}
	}
	if !p.Tailnet {
		res.Cmds = append(res.Cmds, "tailscale down   # day one: the box has never heard of a tailnet")
	}

	for _, step := range []struct {
		path string
		val  any
	}{
		{"vps.ufwDefaultDeny", p.VPS.UFWDefaultDeny},
		{"vps.allowTailscale0", p.VPS.AllowTailscale},
		{"vps.allowPublic22", p.VPS.AllowPublic22},
		{"vps.dockerPublish", p.VPS.DockerPublish},
		{"vps.passwordAuth", p.VPS.PasswordAuth},
		{"vps.permitRoot", p.VPS.PermitRoot},
		{"vps.sshdListen", p.VPS.SSHDListen},
	} {
		r := c.Set(ctx, step.path, step.val)
		res.Cmds = append(res.Cmds, r.Cmds...)
	}

	c.with(func(s *State) { s.ACL.Lock = p.ACL.Lock })
	_ = c.setLock(ctx, p.ACL.Lock)

	c.Observe(ctx)
	return res
}

// Reset puts everything back: clean links, no attacker, the boot configuration.
func (c *Controller) Reset(ctx context.Context) Result {
	res := Result{OK: true, Rule: "reset", Cmds: []string{"make reset   # for the harder version of this"}}
	for _, m := range Catalog {
		if !c.lab.Running(ctx, m.ID) {
			continue
		}
		restore := "tc qdisc del dev eth0 root 2>/dev/null; nft delete table inet lab 2>/dev/null; ip link set eth0 up"
		if gw := c.gatewayFor(m.ID); gw != "" {
			restore += "; ip route replace default via " + gw
		}
		_, _ = c.lab.Sh(ctx, m.ID, restore)
	}
	if c.lab.Running(ctx, "evil-box") {
		_, _ = c.lab.Exec(ctx, "evil-box", "tailscale", "logout")
		_, _ = c.lab.Exec(ctx, "evil-box", "lab-onpath", "off")
	}
	if c.lab.Running(ctx, "lab-ubuntu") {
		_, _ = c.lab.Exec(ctx, "lab-ubuntu", "ip", "route", "replace", "default", "via", c.gatewayFor("lab-ubuntu"))
	}

	// Put the three machines back on the tailnet. The `day-one` configuration
	// takes them off it deliberately, and without this there is no way back to
	// the boot state except loading another configuration — which is not what a
	// button called "Reset everything" should mean.
	for _, m := range []string{"lab-vps", "lab-ubuntu", "lab-roam"} {
		if !c.lab.Running(ctx, m) {
			continue
		}
		_, _ = c.lab.Sh(ctx, m, `tailscale status --json | grep -q '"BackendState": *"Running"' || `+
			`tailscale up --login-server=https://headscale:8443 --authkey="$(cat /lab/state/authkey)" `+
			`--hostname=`+m+` --accept-routes=false --accept-dns=false --timeout=30s`)
	}
	res.Cmds = append(res.Cmds, "tailscale up --login-server=…   # on any machine that was taken off")

	d := defaultState()
	c.with(func(s *State) { s.ACL = d.ACL })
	_ = c.applyPolicy(ctx)
	for _, step := range []struct {
		path string
		val  any
	}{
		{"vps.ufwDefaultDeny", true}, {"vps.allowTailscale0", true},
		{"vps.allowPublic22", true}, {"vps.dockerPublish", false},
		{"vps.passwordAuth", false}, {"vps.permitRoot", false},
		{"vps.sshdListen", "all"},
	} {
		_ = c.Set(ctx, step.path, step.val)
	}
	res.Why = "Links clean, attacker logged out, the boot configuration back. " +
		"`make reset` goes further and throws the containers away."
	c.Observe(ctx)
	return res
}

func mustJSON(v any) string {
	b, _ := json.MarshalIndent(v, "", "  ")
	return string(b)
}
