#!/usr/bin/env bash
# Bring one lab machine up: trust the lab CA, take the route its NAT router
# hands out, start sshd, start tailscaled on a real TUN device, and join the
# lab's coordination server with the pre-auth key the control server wrote.
#
# Nothing here is clever. It is deliberately the same six steps chapter 08
# describes, run in the same order, so the output of `docker compose logs` reads
# like the chapter.
set -euo pipefail

log() { printf '[%s] %s\n' "${LAB_HOSTNAME:-node}" "$*"; }

LAB_ROLE="${LAB_ROLE:-ubuntu}"
LAB_HOSTNAME="${LAB_HOSTNAME:-$(hostname)}"
LAB_LOGIN_SERVER="${LAB_LOGIN_SERVER:-https://headscale:8443}"
STATE_DIR="${LAB_STATE_DIR:-/lab/state}"

# ---- 1 · trust the lab's own CA ----------------------------------------
# The coordination server and its DERP relay speak TLS, because DERP requires
# it. The CA is generated by the control server on first boot and lives only in
# a Docker volume on this machine.
for _ in $(seq 1 60); do
  [ -f "$STATE_DIR/ca/lab-ca.crt" ] && break
  sleep 1
done
if [ -f "$STATE_DIR/ca/lab-ca.crt" ]; then
  cp "$STATE_DIR/ca/lab-ca.crt" /usr/local/share/ca-certificates/lab-ca.crt
  update-ca-certificates >/dev/null 2>&1 || true
  log "trusted the lab CA"
else
  log "WARNING: no lab CA found at $STATE_DIR/ca/lab-ca.crt — this machine will not join"
fi

# ---- 2 · take the route out through this machine's NAT ------------------
# Docker gives every container a default route to its own bridge. The lab
# replaces it with a router container, so this machine reaches the rest of the
# world through a NAT it does not control — which is the only reason NAT
# traversal in this lab means anything.
if [ -n "${LAB_GATEWAY:-}" ]; then
  ip route replace default via "$LAB_GATEWAY"
  log "default route now via $LAB_GATEWAY"
fi

# ---- 3 · sshd -----------------------------------------------------------
# Where chapter 08 leaves a box: keys only, root by key, listening everywhere.
# One file, three settings, rewritten in place by the control server.
mkdir -p /var/run/sshd
printf '%s\n' \
  'PermitRootLogin prohibit-password' \
  'PasswordAuthentication no' \
  'ListenAddress 0.0.0.0' \
  > "${LAB_SSHD_CONF:-/etc/ssh/sshd_config.d/10-lab-runtime.conf}"
/usr/sbin/sshd
log "sshd listening"

# ---- 4 · the host firewall ---------------------------------------------
# Only the public box runs one, exactly as the guide's topology has it: the
# laptop and the roaming client are behind their own NATs and nothing routes to
# them. Keeping that asymmetry means the sandbox's model and this stack agree.
if [ "$LAB_ROLE" = "vps" ]; then
  ufw --force reset       >/dev/null 2>&1 || true
  ufw default deny incoming  >/dev/null 2>&1 || true
  ufw default allow outgoing >/dev/null 2>&1 || true
  ufw allow in on tailscale0 >/dev/null 2>&1 || true
  ufw allow 22/tcp           >/dev/null 2>&1 || true
  ufw --force enable      >/dev/null 2>&1 || true
  log "ufw enabled — default deny in, :22 open, tailscale0 allowed"
fi

# ---- 5 · tailscaled -----------------------------------------------------
mkdir -p /var/lib/tailscale /var/run/tailscale
if [ ! -c /dev/net/tun ]; then
  log "FATAL: /dev/net/tun is missing. This container needs --device /dev/net/tun."
  exit 1
fi

# --no-logs-no-support keeps the lab genuinely offline: without it tailscaled
# spends the first minute trying to reach log.tailscale.com and filling the log
# you are about to read with timeouts.
tailscaled \
  --tun=tailscale0 \
  --state=/var/lib/tailscale/tailscaled.state \
  --socket=/var/run/tailscale/tailscaled.sock \
  --port=41641 \
  --no-logs-no-support \
  >/var/log/tailscaled.log 2>&1 &
log "tailscaled started (log: /var/log/tailscaled.log)"

# ---- 6 · join the tailnet ----------------------------------------------
# The control server creates the user and a reusable pre-auth key once the
# coordination server answers, then drops it here. Waiting on a file keeps the
# dependency one-way and keeps this script free of any API client.
log "waiting for the pre-auth key…"
for _ in $(seq 1 180); do
  [ -s "$STATE_DIR/authkey" ] && break
  sleep 1
done

if [ -s "$STATE_DIR/authkey" ]; then
  AUTHKEY="$(cat "$STATE_DIR/authkey")"
  for attempt in 1 2 3 4 5; do
    if tailscale up \
        --login-server="$LAB_LOGIN_SERVER" \
        --authkey="$AUTHKEY" \
        --hostname="$LAB_HOSTNAME" \
        --accept-routes=false \
        --accept-dns=false \
        --timeout=30s; then
      log "joined the tailnet as $LAB_HOSTNAME"
      break
    fi
    log "tailscale up failed (attempt $attempt) — retrying"
    sleep 5
  done
else
  log "WARNING: no pre-auth key appeared; this machine is not on the tailnet"
fi

tailscale ip -4 2>/dev/null | sed "s/^/[$LAB_HOSTNAME] tailnet address: /" || true

# The control server drives everything from here with `docker exec`.
exec tail -f /var/log/tailscaled.log
